name: "PRs to Google Sheets"
description: "Track PR deployments across environments in Google Sheets"

inputs:
  github-token:
    description: "GitHub token"
    required: true
  spreadsheet-id:
    description: "Google Spreadsheet ID"
    required: true
  google-credentials:
    description: "Google Service Account JSON"
    required: true
  app:
    description: "Application name (Web, Admin, CM)"
    required: true
  environment:
    description: "Deployment environment (Internal, Stage, Production)"
    required: true
  version:
    description: "Version number being deployed (e.g., #20241213.31712.0)"
    required: false
    default: ""
  sheet-name:
    description: "Sheet tab name"
    required: false
    default: "Next"
  base-tag:
    description: "Previous deployment tag to compare from"
    required: false
    default: ""
  head-tag:
    description: "Current deployment tag"
    required: false
    default: ""
  jira-tickets:
    description: "Comma-separated Jira tickets (e.g., ADV-123,ADV-456)"
    required: false
    default: ""

runs:
  using: "node20"
  main: "dist/index.js"