name: "PRs to Google Sheets"
description: "Track PR deployments across environments in Google Sheets"

inputs:
  github-token:
    description: "GitHub token"
    required: true
  spreadsheet-id:
    description: "Google Spreadsheet ID"
    required: true
  google-credentials:
    description: "Google Service Account JSON"
    required: true
  app:
    description: "Application name (e.g., frontend, backend)"
    required: true
  sheet-name:
    description: "Sheet tab name"
    required: false
    default: "Next"

runs:
  using: "node20"
  main: "dist/index.js"